CREATE DATABASE campus;

CREATE TABLE campers(
    id INT primary key AUTO_INCREMENT,
    NOMBRES VARCHAR (50) NOT NULL,
    DIRECCION VARCHAR (50) NOT NULL,
    LOGROS VARCHAR (60) NOT NULL,
    ESPECIALIDAD VARCHAR (50) NOT NULL, 
    SKILLS INT NOT NULL,
    SER INT NOT NULL,
    INGLES VARCHAR (50) NOT NULL,
    REVIEW INT NOT NULL,
);